version: 2.1

orbs:
  maven: circleci/maven@1.2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - run: mvn test

workflows:
  test-and-build:
    jobs:
      - test
